# Generated by Django 6.0.1 on 2026-01-27 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=100)),
                ('class_name', models.CharField(db_column='class', max_length=50)),
                ('date', models.DateField()),
                ('caused_by', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'damaged_entry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DamagedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparatus_name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('damaged_entry', models.ForeignKey(db_column='damaged_entry_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='damaged_items', to='damaged_entry.damagedentry')),
            ],
            options={
                'db_table': 'damaged_item',
                'managed': True,
            },
        ),
    ]
