# Generated by Django 6.0.1 on 2026-02-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damaged_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagedentry',
            name='caused_by',
        ),
        migrations.AddField(
            model_name='damageditem',
            name='caused_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
