# Generated by Django 6.0.1 on 2026-02-22 00:45

from django.db import migrations
import random


def populate_caused_by(apps, schema_editor):
    DamagedItem = apps.get_model('damaged_entry', 'DamagedItem')
    names = ['Nithish', 'Gowtham', 'Sarathy', 'Dharani']
    
    for item in DamagedItem.objects.all():
        item.caused_by = random.choice(names)
        item.save()


def reverse_populate_caused_by(apps, schema_editor):
    DamagedItem = apps.get_model('damaged_entry', 'DamagedItem')
    DamagedItem.objects.all().update(caused_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('damaged_entry', '0002_move_caused_by_to_item'),
    ]

    operations = [
        migrations.RunPython(populate_caused_by, reverse_populate_caused_by),
    ]
