# Generated by Django 5.2.8 on 2026-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damaged_entry', '0003_populate_caused_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedentry',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
