# Generated by Django 5.2.8 on 2026-07-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damaged_entry', '0004_create_damaged_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagedentry',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='damageditem',
            options={'managed': False},
        ),
    ]
