# Generated by Django 5.2.8 on 2026-02-13 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='class_name',
            field=models.CharField(blank=True, choices=[('I B.Sc Chemistry', 'I B.Sc Chemistry'), ('II B.Sc Chemistry', 'II B.Sc Chemistry'), ('III B.Sc Chemistry', 'III B.Sc Chemistry'), ('I M.Sc Chemistry', 'I M.Sc Chemistry'), ('II M.Sc Chemistry', 'II M.Sc Chemistry')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='request_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
