# Generated by Django 5.2.8 on 2026-02-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0002_stockrequest_class_name_stockrequest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='class_name',
            field=models.CharField(choices=[('I B.Sc Chemistry', 'I B.Sc Chemistry'), ('II B.Sc Chemistry', 'II B.Sc Chemistry'), ('III B.Sc Chemistry', 'III B.Sc Chemistry'), ('I M.Sc Chemistry', 'I M.Sc Chemistry'), ('II M.Sc Chemistry', 'II M.Sc Chemistry')], default='I B.Sc Chemistry', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='request_id',
            field=models.CharField(default='AUTO', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
