# Generated by Django 5.2.8 on 2026-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0003_alter_stockrequest_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
