# Generated by Django 5.2.8 on 2026-02-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0004_alter_stockrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='viewed_by_requester',
            field=models.BooleanField(default=False),
        ),
    ]
