# Generated by Django 5.2.8 on 2026-02-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0005_stockrequest_viewed_by_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('issued', 'Issued')], default='pending', max_length=20),
        ),
    ]
