# Generated by Django 5.2.8 on 2026-02-18 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0006_alter_stockrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequestchemicalitem',
            name='actual_used_quantity_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('reported', 'Reported'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='IssueRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=20)),
                ('staff_name', models.CharField(max_length=64)),
                ('class_name', models.CharField(max_length=50)),
                ('issued_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_register_entry', to='stock_request.stockrequest')),
            ],
            options={
                'db_table': 'chemical_issue_register',
                'ordering': ['-completed_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IssueRegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=64)),
                ('requested_quantity_ml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_used_quantity_ml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returned_quantity_ml', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additionally_used_ml', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issue_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_request.issueregister')),
            ],
            options={
                'db_table': 'chemical_issue_register_item',
                'managed': True,
            },
        ),
    ]
