# Generated by Django 5.2.8 on 2026-02-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0007_stockrequest_completed_at_stockrequest_issued_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueChemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=64)),
                ('issued_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('returned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'issue_chemicals',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='issueregister',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='IssueRegisterItem',
        ),
    ]
