# Generated by Django

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0008_issuechemicals_alter_issueregister_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='date',
            field=models.DateField(default=date.today),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
