# Generated by Django 5.2.8 on 2026-05-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0010_issueregister_add_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='issueregister',
            table='issue_register',
        ),
    ]
