# Generated by Django 5.2.8 on 2026-07-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0012_fix_column_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrequest',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockrequestapparatusitem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stockrequestchemicalitem',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='issueregister',
            table='issue_register',
        ),
    ]
