# Generated by Django 6.0.1 on 2026-01-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableApparatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparatus_name', models.CharField(max_length=64)),
                ('available_quantity_pieces', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('reorder_level', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'available_apparatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvailableChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=64)),
                ('available_quantity_ml', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateField(auto_now=True)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'available_chemicals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LowStockApparatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparatus_name', models.CharField(max_length=64)),
                ('current_quantity_pieces', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('last_checked', models.DateField()),
            ],
            options={
                'db_table': 'low_stock_apparatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LowStockChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=64)),
                ('current_quantity_ml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_checked', models.DateField()),
            ],
            options={
                'db_table': 'low_stock_chemicals',
                'managed': True,
            },
        ),
    ]
