# Generated by Django 6.0.1 on 2026-01-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_common_reorder_level', models.BooleanField(default=False)),
                ('common_chemical_reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('common_apparatus_reorder_level', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'lab_configuration',
                'managed': True,
            },
        ),
    ]
