# Generated by Django 5.2.8 on 2026-01-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_labconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableapparatus',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='availablechemical',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lowstockapparatus',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lowstockchemical',
            options={'managed': True},
        ),
    ]
