# Generated by Django 6.0.1 on 2026-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_availableapparatus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablechemical',
            old_name='available_quantity_ml',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='lowstockchemical',
            old_name='current_quantity_ml',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='availablechemical',
            name='unit',
            field=models.CharField(choices=[('ml', 'mL'), ('g', 'g')], default='ml', max_length=2),
        ),
        migrations.AddField(
            model_name='lowstockchemical',
            name='unit',
            field=models.CharField(choices=[('ml', 'mL'), ('g', 'g')], default='ml', max_length=2),
        ),
    ]
