# Generated by Django 5.2.8 on 2025-12-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'stock_register',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApparatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparatus_name', models.CharField(max_length=64)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_pieces', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_register', models.ForeignKey(db_column='stock_register_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='apparatus_items', to='stock_register.stockregister')),
            ],
            options={
                'db_table': 'apparatus_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChemicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=64)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_ml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_register', models.ForeignKey(db_column='stock_register_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chemical_items', to='stock_register.stockregister')),
            ],
            options={
                'db_table': 'chemical_item',
                'managed': True,
            },
        ),
    ]
