# Generated by Django 5.2.8 on 2026-02-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_register', '0002_add_stock_register_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparatusitem',
            name='make',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalitem',
            name='make',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalitem',
            name='stock_register',
            field=models.ForeignKey(db_column='stock_register_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chemical_items', to='stock_register.stockregister'),
        ),
        migrations.AlterField(
            model_name='stockregister',
            name='supplier_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
