# Generated by Django 5.2.8 on 2026-06-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_register', '0003_alter_apparatusitem_make_alter_chemicalitem_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockregister',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
