# Generated by Django 6.0.1 on 2026-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_register', '0004_stockregister_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicalitem',
            old_name='quantity_ml',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='chemicalitem',
            name='unit',
            field=models.CharField(choices=[('ml', 'mL'), ('g', 'g')], default='ml', max_length=2),
        ),
    ]
