# Generated by Django 5.2.8 on 2026-07-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_register', '0005_create_inventory_triggers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apparatusitem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chemicalitem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stockregister',
            options={'managed': False},
        ),
    ]
