# Generated by Django 6.0.1 on 2026-07-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_register', '0006_alter_apparatusitem_options_and_more'),
        ('stock_register', '0006_stock_register_v2_schema'),
    ]

    operations = [
    ]
