# Generated by Django 5.2.8 on 2026-02-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_passwordresettoken_id_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
