# Generated by Django 6.0.1 on 2026-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_is_first_login_and_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('bsc', 'B.Sc Chemistry'), ('msc', 'M.Sc Chemistry'), ('phd', 'PhD')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'degree_class',
                'ordering': ['degree', 'name'],
                'managed': True,
                'unique_together': {('degree', 'name')},
            },
        ),
    ]
