# Generated by Django 5.2.8 on 2026-08-05 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_degree_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_password_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'change_password_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
