# Generated by Django 6.0.1 on 2026-06-30 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('PASSWORD_CHANGED', 'Password Changed'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('STOCK_ENTRY_ADDED', 'Stock Entry Added'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_SUBMITTED', 'Request Submitted'), ('REQUEST_CANCELLED', 'Request Cancelled'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_ISSUED', 'Request Issued'), ('USAGE_REPORTED', 'Usage Reported'), ('REQUEST_COMPLETED', 'Request Completed'), ('DAMAGE_REPORTED', 'Damage Reported'), ('REPORT_GENERATED', 'Report Generated')], max_length=60)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
