from .login_page import LoginPage
from .change_password_page import ChangePasswordPage
from .inventory_page import InventoryPage
from .stock_register_page import StockRegisterPage, NewStockRegisterPage
from .stock_request_page import StockRequestListPage, NewChemicalRequestPage, StockRequestDetailPage
from .damaged_entry_page import DamagedEntryPage, NewDamagedEntryPage
from .service_entry_page import NewServiceEntryPage, ServiceEntryDetailPage
from .issue_register_page import IssueRegisterPage, IssueRegisterDetailPage
from .user_management_page import UserManagementPage, CreateUserPage, SettingsPage
from .notification_center import NotificationCenter
